export const initialFieldJson = {
  text: {
    type: "text",
    name: "Your name",
    id: "bd8d58f7-f12f-46e9-bc85-693603ddb534",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    show_char_limit: false,
    src: false,
    logic: {
      conditions: null,
      actions: [],
    },
    max_char_limit: 2000,
  },
  date: {
    type: "date",
    name: "Date",
    id: "4c25607c-97e0-4fcf-bfda-d7f907a57390",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  url: {
    type: "url",
    name: "Link",
    id: "40be1b72-eda5-4b4c-bb0e-d2dae92fc148",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    show_char_limit: false,
    src: false,
    logic: {
      conditions: null,
      actions: [],
    },
    max_char_limit: 2000,
  },
  phone_number: {
    type: "phone_number",
    name: "Phone Number",
    id: "1fdfaa23-45b6-400c-93b0-f1bba8fad230",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  email: {
    type: "email",
    name: "Email",
    id: "7c5c0824-9b21-42e7-8e27-f0f64e3d1331",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    show_char_limit: false,
    src: false,
    logic: {
      conditions: null,
      actions: [],
    },
    max_char_limit: 2000,
  },
  checkbox: {
    type: "checkbox",
    name: "Checkbox",
    id: "c360e8cd-600d-42f1-aebb-118ca0c1b402",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  select: {
    type: "select",
    name: "Select",
    id: "34eefdff-ad72-4fc8-9474-fc667f555c86",
    hidden: false,
    select: {
      options: [],
    },
    help_position: "below_input",
    width: "full",
    align: "left",
    selectedOptionType: "custom",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  multi_select: {
    type: "multi_select",
    name: "Multi Select",
    id: "a1472385-512f-4b06-912b-b97cf23cc3a5",
    hidden: false,
    multi_select: {
      options: [],
    },
    help_position: "below_input",
    width: "full",
    align: "left",
    selectedOptionType: "custom",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  number: {
    type: "number",
    name: "Number",
    id: "d2de5910-9327-40d5-ad57-19edcf6f3f0e",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    show_char_limit: false,
    src: false,
    logic: {
      conditions: null,
      actions: [],
    },
    max_char_limit: 2000,
  },
  files: {
    type: "files",
    name: "Files",
    id: "7d14fa01-6c4e-43d5-b4d1-4a13608dec40",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  location: {
    type: "location",
    name: "Location",
    id: "588af9b0-1c6c-4403-90fc-5eaea208ced4",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  "nf-image": {
    type: "nf-image",
    name: "Image",
    src: null,
    alt: "Image",
    id: "f1cea992-a005-4e0f-a722-34fbd41da4fc",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  "nf-text": {
    type: "nf-text",
    name: "Text Block",
    content: "<p>This is a text block.</p>",
    id: "8f01d1de-1632-420f-ad60-8018f5c92019",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  "nf-page-break": {
    type: "nf-page-break",
    name: "Page Break",
    next_btn_text: "Next",
    previous_btn_text: "Previous",
    id: "cacaa59f-6330-425a-a514-c176b28202ed",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
  "nf-divider": {
    type: "nf-divider",
    name: "Divider",
    id: "c141dd69-4984-4e1a-bab4-b6af434977b8",
    hidden: false,
    help_position: "below_input",
    width: "full",
    align: "left",
    logic: {
      conditions: null,
      actions: [],
    },
  },
};
