name: CI Pipeline

on:
  pull_request:
    branches: ["main", "development", "stage", "uat"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Pre Build
        run: npm run cleanup

      - name: Build Project
        run: npm run build

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply auto-cleanup changes"

      # - name: Send Slack Notification
      #   if: always()
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     payload: |
      #       {
      #         "text": "Build Status: ${{ job.status }} for ${{ github.repository }} on branch ${{ github.ref_name }}"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}